# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/asaf-kali/generic-iterative-stemmer
    rev: 916687483b9683d3b8e16466ebebfabaf54dd4d8
    hooks:
      - id: custom-lint
