name: Tests

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set swap space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10
      - name: Set up python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: CI setup
        run: |
          pip install pybind11 wheel
      - name: Install dependencies
        run: |
          make install-test
      - name: Run tests
        run: |
          make test
